[package]
name = "ptc"
version = "0.1.0"
authors = ["Alexander Jackson <alexanderjackson@protonmail.com"]
edition = "2018"
build = "build.rs"

[build-dependencies]
lalrpop = "0.19.5"

[dependencies]
lalrpop-util = "0.19.5"
regex = "1.4.5"
pico-args = "0.4.0"
lazy_static = "1.4.0"
