[package]
name = "ptc"
version = "0.1.0"
authors = ["Alexander Jackson <alexanderjackson@protonmail.com"]
build = "build.rs"

[build-dependencies.lalrpop]
version = "0.17.2"

[dependencies]
lalrpop-util = "0.17.2"
regex = "1"
