[package]
name = "ptc"
version = "0.1.0"
authors = ["Alexander Jackson <alexanderjackson@protonmail.com"]
build = "build.rs"
edition = "2021"

[build-dependencies.lalrpop]
version = "0.20.0"

[dependencies]
lalrpop-util = "0.20.0"
regex = "1.10.2"
pico-args = "0.5.0"
